### PR TITLE
Adjust design according to design dept.

### PR DESCRIPTION
**Pull request by seanmtracey**
Doesn't work for Safari `Version 9.0.3 (10601.4.4)` _Oh, Apple_, but it seems the current version doesn't either. Working on a fallback now.

screen-shot-2017-05-16-at-11 15 01

### CODE REVIEW

**Comment by seanmtracey** [comment]
Update: Flexbox fix for Safari >= 9 has been included.

**Comment by railsagainstignorance** [comment]
the homepage article links don't go to the article

**Comment by seanmtracey** [comment]
Whoops! Should be fixed.

**Comment by railsagainstignorance** [comment]
the excerpt text of each tile in the homepage no longer links to the article, just the title+teaser

**Comment by seanmtracey** [comment]
That's intentional. Keeps in line with how o-teaser works across the FT.

**Comment by railsagainstignorance** [comment]
ugh. ok. fine. I'll wait til no-one is looking then link from the excerpt text.
Meanwhile (and with that exception), LGTM.

**Pull request merged**
